### ISSUE TITLE
Enable passing an app that should have the opportunity to serve before any of polyserve does

### ISSUE THREAD

**Issue by rictic** [Polymer/polyserve#138]

**Comment by justinfagnani** [comment]
I'm not sure we want to do this in polyserve. I think WCT should wrap polyserve's apps with additional routes laid on top. Let's see if we can move to that pattern before the next release of everything.

**Comment by rictic** [comment]
+1. This can supersede additionalRoutes

**Comment by ghuntley** [comment]
Any update here? What's the direction one should take if sending in a pull-request?

**Comment by justinfagnani** [comment]
I think me comment above still stands, though the issue is certainly open for discussion.

Given Express's options for composing handlers, is a special API in polyserve warranted?

**Comment by ctreatma** [comment]
We're running into problems related to this with the `web-component-tester-istanbul` plugin, because that plugin [registers middleware in order to instrument code for coverage](https://github.com/thedeeno/web-component-tester-istanbul/blob/master/lib/plugin.js#L40), but the app returned by `makeApp` [already has a `GET` handler registered for `*`](https://github.com/Polymer/polyserve/blob/30a67fa7ff5ecdd3971f45fed08e2fad80f30283/src/make_app.ts#L63), and that handler finishes the request without delegating to other middleware, so the instrumentation handler will never get called.

**Comment by usergenic** [comment]
This was flagged this morning to me and I wanted to look deeper into since I've been getting deeper into WCT and Polyserve lately.

After looking at @ctreatma's comment it seems like our catch-all `/*` routes need to tail-call into post-processing middleware if we are going to be able to support hooks like the wct-istanbul plugin is trying to do.  Its not so much that polyserve is inadequate, but because wct doesn't really provide a layer for mounting other apps onto its webserver, i.e. polyserve, we could see if we can provide what's needed by doing something along the lines of adding `next()` calls in our handlers.

Labeling issue and prioritizing.

**Comment by usergenic** [comment]
This is now essentially implemented in #228 with the ability to map different app(s) in place of the one(s) being created when startServers is invoked.  Release should happen next week.
